# Generated by Django 4.0.3 on 2022-04-08 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssignedTo',
        ),
        migrations.AlterModelOptions(
            name='incoming',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='incoming',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='author',
            field=models.CharField(max_length=255),
        ),
    ]
