# Generated by Django 4.0.3 on 2022-04-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0003_assignedto_incoming_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedto',
            old_name='assigned_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='assignedto',
            old_name='assigned_by',
            new_name='created_by',
        ),
    ]
