# Generated by Django 4.0.4 on 2022-04-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0006_alter_incoming_created_by_alter_incoming_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='incoming/'),
        ),
    ]
