# Generated by Django 4.0.4 on 2022-04-13 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incoming', '0007_incoming_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='incoming_documents/'),
        ),
    ]
